notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

deploy:
  provider: apm
  api_key:
    secure: "MvxKJAUglt0zbMBMOEaJFwqK8ptYlJD1mSyTNZ7x0T02CdST4Fx70AK3x79odI0o8YUGrLKfFdJyBrGkme9ainYDeomIu0O4QTZ2tGdpLsbTop4dDnQbYjyba/gI6aK+4x9WJ167CY3bYLs+0w3P4HMhtvsvQuLAhpZqbZykOgQ="
  edge:
    source: kepler0/dpl
    branch: apm
  on:
    tags: true
