version: "{build}"

os: Windows Server 2012 R2

install:
  - choco install atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm clean"
  - "%LOCALAPPDATA%/atom/bin/apm install"
  - choco install https://chocolatey.org/api/v2/package/clang/3.6.0 -y --pre

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"

test: off

deploy: off
