version: "{build}"

os: Windows Server 2012 R2

install:
  - choco install atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm clean"
  - "%LOCALAPPDATA%/atom/bin/apm install"
  - iex ((new-object net.webclient).DownloadString('http://llvm.org/releases/3.7.0/LLVM-3.7.0-win32.exe'))

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"

test: off

deploy: off
